In [1]:
# import libraries

import pandas as pd

In [2]:
url = 'https://en.wikipedia.org/wiki/Economy_of_Thailand'

In [3]:
tables = pd.read_html(url) # read data

In [4]:
tables

[                                                    0  \
 0             Bangkok, the commercial hub of Thailand
 1                                            Currency
 2                                         Fiscal year
 3                                 Trade organisations
 4                                       Country group
 5                                          Statistics
 6                                          Population
 7                                                 GDP
 8                                            GDP rank
 9                                          GDP growth
 10                                     GDP per capita
 11                                GDP per capita rank
 12                                      GDP by sector
 13                                    Inflation (CPI)
 14                      Population below poverty line
 15                                   Gini coefficient
 16                            Human Development Index
 17                                       Labour force
 18                                       Unemployment
 19                                    Main industries
 20                        Ease-of-doing-business rank
 21                                           External
 22                                            Exports
 23                                       Export goods
 24                               Main export partners
 25                                            Imports
 26                                       Import goods
 27                               Main import partners
 28                                          FDI stock
 29                                Gross external debt
 30                                    Public finances
 31                                    Government debt
 32                                           Revenues
 33                                           Expenses
 34                                       Economic aid
 35                                      Credit rating
 36                                   Foreign reserves
 37  Main data source: CIA World Fact Book All valu...

                                                     1
 0             Bangkok, the commercial hub of Thailand
 1                                  Thai baht (THB, ฿)
 2                            1 October – 30 September
 3                     WTO, APEC, IOR-ARC, ASEAN, RCEP
 4   .mw-parser-output .plainlist ol,.mw-parser-out...
 5                                          Statistics
 6                                69,950,844 (2021)[3]
 7   $574 billion (nominal; 2023 est.)[4]  $1.591 t...
 8               27th (nominal; 2023) 23st (PPP; 2023)
 9    1.5% (2021)[5]  2.8% (2022f)[5]  3.7% (2023f)[5]
 10  $8,181 (nominal; 2023 est.)[4]  $22,675 (PPP; ...
 11              84th (nominal; 2023) 74th (PPP; 2023)
 12  Agriculture: 8.4% Industry: 39.2% Services: 52...
 13                                   5.02% (Jan 2023)
 14  9.9% (2018)[7]  8.6% on less than $5.50/day (2...
 15                  34.9 medium (2019, World Bank)[9]
 16  0.800 very high (2021)[10] (66th)  0.646 mediu...
 17  38,917,441 (2019)[12]  67.3% employment rate (...
 18                               1.1% (2020 est.)[14]
 19  Automobiles and automotive parts (11%), financ...
 20                         21st (very easy, 2020)[15]
 21                                           External
 22                         $287.07 billion (2022)[16]
 23  machinery (23%), electronics (19%), foods and ...
 24  .mw-parser-output .treeview ul{padding:0;margi...
 25                         $303.19 billion (2022)[16]
 26  Capital and intermediate goods, raw materials,...
 27  China 24.3%  ASEAN 17.5%  Japan 11.4%  Europea...
 28                     $205.5 billion (2017 est.)[17]
 29                  $163.402.95 billion (Q1 2019)[18]
 30                                    Public finances
 31                              44.01% (May 2020)[19]
 32                    THB 2.563 trillion (FY2019)[20]
 33                    THB 2.788 trillion (FY2019)[21]
 34                                               None
 35  Standard & Poor's:[22][23] A- (Domestic) BBB+ ...
 36      US$266.09 billion (net amount, June 2020)[26]
 37  Main data source: CIA World Fact Book All valu...  ,
     Year  GDP (in Bil. US$PPP)  GDP per capita (in US$ PPP)  \
 0   1980                  74.7                       1576.1
 1   1981                  86.6                       1791.2
 2   1982                  96.8                       1965.9
 3   1983                 106.2                       2117.4
 4   1984                 116.4                       2278.4
 5   1985                 125.7                       2415.5
 6   1986                 135.3                       2553.7
 7   1987                 151.8                       2814.7
 8   1988                 178.1                       3244.3
 9   1989                 207.6                       3722.9
 10  1990                 240.4                       4251.2
 11  1991                 269.5                       4708.1
 12  1992                 301.0                       5207.2
 13  1993                 334.9                       5740.8
 14  1994                 369.4                       6274.5
 15  1995                 407.8                       6857.3
 16  1996                 438.7                       7296.2
 17  1997                 434.0                       7132.7
 18  1998                 405.4                       6582.4
 19  1999                 429.9                       6900.4
 20  2000                 459.2                       7294.6
 21  2001                 485.7                       7644.6
 22  2002                 523.6                       8173.0
 23  2003                 572.4                       8866.9
 24  2004                 624.7                       9611.3
 25  2005                 671.3                      10261.3
 26  2006                 726.3                      11036.6
 27  2007                 786.5                      11884.2
 28  2008                 815.4                      12256.5
 29  2009                 815.0                      12188.3
 30  2010                 886.8                      13196.8
 31  2011                 912.8                      13519.1
 32  2012                1008.8                      14871.0
 33  2013                1049.9                      15407.7
 34  2014                1059.4                      15480.2
 35  2015                1087.2                      15822.4
 36  2016                1146.0                      16616.2
 37  2017                1205.8                      17423.0
 38  2018                1286.8                      18533.9
 39  2019                1338.0                      19216.9
 40  2020                1270.2                      18197.9
 41  2021                1343.3                      19203.3
 42  2022                1479.6                      21114.2
 43  2023                1589.3                      22644.8
 44  2024                1680.3                      23912.8
 45  2025                1768.3                      25142.7
 46  2026                1859.5                      26424.0
 47  2027                1953.0                      27743.5

     GDP (in Bil. US$nominal)  GDP per capita (in US$ nominal)  \
 0                       33.4                            705.5
 1                       36.0                            744.9
 2                       37.8                            767.4
 3                       41.4                            824.4
 4                       43.2                            845.1
 5                       40.2                            772.4
 6                       44.5                            840.3
 7                       52.2                            967.7
 8                       63.7                           1160.5
 9                       74.6                           1338.3
 10                      88.5                           1564.2
 11                     101.2                           1769.0
 12                     115.6                           1999.2
 13                     128.9                           2209.4
 14                     146.7                           2491.4
 15                     169.3                           2846.6
 16                     183.0                           3044.0
 17                     150.2                           2468.2
 18                     113.7                           1845.8
 19                     126.5                           2031.2
 20                     126.1                           2003.6
 21                     120.1                           1890.3
 22                     134.2                           2094.3
 23                     152.1                           2357.0
 24                     172.8                           2657.9
 25                     189.1                           2890.5
 26                     221.6                           3366.8
 27                     263.0                           3974.0
 28                     291.0                           4373.5
 29                     281.4                           4208.4
 30                     340.9                           5073.7
 31                     370.9                           5493.7
 32                     397.7                           5863.0
 33                     420.4                           6168.7
 34                     407.4                           5952.4
 35                     401.1                           5837.8
 36                     413.5                           5995.2
 37                     456.5                           6596.2
 38                     506.5                           7296.0
 39                     544.0                           7813.6
 40                     499.8                           7159.7
 41                     505.9                           7232.3
 42                     534.8                           7630.9
 43                     580.7                           8273.9
 44                     597.6                           8504.4
 45                     640.2                           9103.0
 46                     673.0                           9562.9
 47                     732.2                          10401.9

    GDP growth (real) Inflation rate (in Percent) Unemployment (in Percent)  \
 0               4.6%                       19.7%                       NaN
 1               5.9%                       12.7%                       NaN
 2               5.4%                        5.3%                       NaN
 3               5.6%                        3.7%                       NaN
 4               5.8%                        0.8%                       NaN
 5               4.6%                        2.4%                       NaN
 6               5.5%                        1.8%                       NaN
 7               9.5%                        2.5%                       NaN
 8              13.3%                        3.9%                       NaN
 9              12.2%                        5.4%                       NaN
 10             11.6%                        5.8%                       NaN
 11              8.4%                        5.7%                       NaN
 12              9.2%                        4.1%                       NaN
 13              8.7%                        3.3%                       NaN
 14              8.0%                        5.1%                       NaN
 15              8.1%                        5.8%                       NaN
 16              5.7%                        5.8%                       NaN
 17             -2.8%                        5.6%                       NaN
 18             -7.6%                        8.0%                       NaN
 19              4.6%                        0.2%                       NaN
 20              4.5%                        1.7%                       NaN
 21              3.4%                        1.6%                      3.3%
 22              6.1%                        0.7%                      2.4%
 23              7.2%                        1.8%                      2.2%
 24              6.3%                        2.8%                      2.1%
 25              4.2%                        4.5%                      1.9%
 26              5.0%                        4.7%                      1.5%
 27              5.4%                        2.2%                      1.4%
 28              1.7%                        5.5%                      1.4%
 29             -0.7%                       -0.9%                      1.5%
 30              7.5%                        3.3%                      1.1%
 31              0.8%                        3.8%                      0.7%
 32              7.2%                        3.0%                      0.7%
 33              2.7%                        2.2%                      0.7%
 34              1.0%                        1.9%                      0.8%
 35              3.1%                       -0.9%                      0.9%
 36              3.4%                        0.2%                      1.0%
 37              4.2%                        0.7%                      1.2%
 38              4.2%                        1.1%                      1.1%
 39              2.2%                        0.7%                      1.0%
 40             -6.2%                       -0.8%                      2.0%
 41              1.5%                        1.2%                      1.5%
 42              2.8%                        6.3%                      1.0%
 43              3.7%                        2.8%                      1.0%
 44              3.6%                        1.5%                      1.0%
 45              3.3%                        2.3%                      1.0%
 46              3.2%                        2.0%                      1.0%
 47              3.0%                        2.0%                      1.0%

    Government debt (in % of GDP)
 0                            NaN
 1                            NaN
 2                            NaN
 3                            NaN
 4                            NaN
 5                            NaN
 6                            NaN
 7                            NaN
 8                            NaN
 9                            NaN
 10                           NaN
 11                           NaN
 12                           NaN
 13                           NaN
 14                           NaN
 15                           NaN
 16                         15.2%
 17                         40.5%
 18                         49.9%
 19                         56.6%
 20                         57.8%
 21                         57.5%
 22                         54.9%
 23                         47.5%
 24                         46.3%
 25                         45.5%
 26                         39.2%
 27                         36.0%
 28                         34.9%
 29                         42.4%
 30                         39.8%
 31                         39.1%
 32                         41.9%
 33                         42.2%
 34                         43.3%
 35                         42.6%
 36                         41.7%
 37                         41.8%
 38                         41.9%
 39                         41.1%
 40                         49.5%
 41                         58.4%
 42                         61.5%
 43                         61.4%
 44                         61.3%
 45                         60.9%
 46                         59.3%
 47                         59.5%  ,
    Year  Value (THB billion) as % of GDP
 0  2011              566.355       5.37%
 1  2012              751.132       6.08%
 2  2013              812.085       6.29%
 3  2014              832.750       6.31%
 4  2015              892.623       6.53%
 5  2016              944.434       6.58%
 6  2017              881.380       5.90%
 7  2018              882.083         NaN,
     Year    Units Production for          Export value (THB billion)  \
     Year    Units       Domestic   Export Export value (THB billion)
 0   2005  1125316         690409   434907                    203.025
 1   2006  1188044         646838   541206                    240.764
 2   2007  1287379         598287   689092                    306.595
 3   2008  1394029         610317   783712                    351.326
 4   2009   999378         447318   552060                    251.342
 5   2010  1645304         750614   894690                    404.659
 6   2011  1457795         723845   733950                    343.383
 7   2012  2453717        1432052  1021665                    490.134
 8   2013  2457086        1335783  1121303                    512.186
 9   2014  1880007         757853  1122154                    527.423
 10  2015  1913002         712028  1200974                    592.550
 11  2016  1944417         776843  1167574                    631.845
 12  2017  1988823         862391  1126432                    603.037
 13  2018  2167694        1024961  1142733                    594.809

    Export value as % of GDP
    Export value as % of GDP
 0                     2.86%
 1                     3.07%
 2                     3.60%
 3                     3.78%
 4                     2.78%
 5                     4.00%
 6                     3.26%
 7                     3.97%
 8                     3.97%
 9                     3.99%
 10                    4.33%
 11                    4.40%
 12                    4.04%
 13                      NaN  ,
          Country  Total Trade Value  Import Value  Export Value  Balance
 0          China             128.24         66.43         61.82    -4.61
 1  United States              65.00         14.58         50.43    35.85
 2          Japan              61.92         35.57         26.35    -9.22
 3       Malaysia              23.05         12.05         11.00    -1.05
 4      Australia              17.99          6.42         11.57     5.15
 5      Indonesia              17.37          8.22          9.15     0.93
 6      Singapore              17.15          7.34          9.81     2.46
 7    South Korea              16.90          9.90          7.01    -2.89
 8      Hong Kong              16.51          2.84         13.67    10.84
 9          India              15.08          6.41          8.67     2.26,
    .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}vteThailand articles  \
 0                                             History
 1                                          Chronology
 2                                            By topic
 3                                           Geography
 4   Addresses Borders Cities and towns Climate Ear...
 5                                            Politics
 6   Administrative divisions Cabinet Constitution ...
 7                                             Economy
 8   Agriculture Baht (currency) Banks Central bank...
 9                                             Society

In [5]:
type(tables)

list

In [6]:
len(tables) # how many table in this page

14

In [7]:
type(tables[0]) # type of each table

pandas.core.frame.DataFrame

In [8]:
tables[0].head()

,0,1
0,"Bangkok, the commercial hub of Thailand","Bangkok, the commercial hub of Thailand"
1,Currency,"Thai baht (THB, ฿)"
2,Fiscal year,1 October – 30 September
3,Trade organisations,"WTO, APEC, IOR-ARC, ASEAN, RCEP"
4,Country group,".mw-parser-output .plainlist ol,.mw-parser-out..."

In [9]:
tables[1].head()

,Year,GDP (in Bil. US$PPP),GDP per capita (in US$ PPP),GDP (in Bil. US$nominal),GDP per capita (in US$ nominal),GDP growth (real),Inflation rate (in Percent),Unemployment (in Percent),Government debt (in % of GDP)
0,1980,74.7,1576.1,33.4,705.5,4.6%,19.7%,NaN,NaN
1,1981,86.6,1791.2,36.0,744.9,5.9%,12.7%,NaN,NaN
2,1982,96.8,1965.9,37.8,767.4,5.4%,5.3%,NaN,NaN
3,1983,106.2,2117.4,41.4,824.4,5.6%,3.7%,NaN,NaN
4,1984,116.4,2278.4,43.2,845.1,5.8%,0.8%,NaN,NaN

In [10]:
tables[2].head()

   Year  Value (THB billion) as % of GDP
0  2011              566.355       5.37%
1  2012              751.132       6.08%
2  2013              812.085       6.29%
3  2014              832.750       6.31%
4  2015              892.623       6.53%

In [11]:
tables[3].head()

   Year    Units Production for         Export value (THB billion)  \
   Year    Units       Domestic  Export Export value (THB billion)
0  2005  1125316         690409  434907                    203.025
1  2006  1188044         646838  541206                    240.764
2  2007  1287379         598287  689092                    306.595
3  2008  1394029         610317  783712                    351.326
4  2009   999378         447318  552060                    251.342

  Export value as % of GDP
  Export value as % of GDP
0                    2.86%
1                    3.07%
2                    3.60%
3                    3.78%
4                    2.78%

In [12]:
# assign table to data

data = tables[2]

In [13]:
type(data)

pandas.core.frame.DataFrame

In [14]:
data.dtypes

Year                     int64
Value (THB billion)    float64
as % of GDP             object
dtype: object

In [15]:
# convert string to numeric

data_list = data.values.tolist()[0:] # prepare list of lists of data

In [16]:
data_list[0]

[2011, 566.355, '5.37%']

In [17]:
data_list # each list represrnt a row data

[[2011, 566.355, '5.37%'],
 [2012, 751.132, '6.08%'],
 [2013, 812.085, '6.29%'],
 [2014, 832.75, '6.31%'],
 [2015, 892.623, '6.53%'],
 [2016, 944.434, '6.58%'],
 [2017, 881.38, '5.90%'],
 [2018, 882.083, nan]]

In [18]:
data_list[-1]

[2018, 882.083, nan]

In [20]:
data.items = []

for item in data_list:
    government_debt_str = item[-3]
    print(type(government_debt_str), government_debt_str)

<class 'int'> 2011
<class 'int'> 2012
<class 'int'> 2013
<class 'int'> 2014
<class 'int'> 2015
<class 'int'> 2016
<class 'int'> 2017
<class 'int'> 2018

In [25]:
data.items = []

for item in data_list:
    inflation_rate_str = item[-1]
    print(type(inflation_rate_str), inflation_rate_str)

<class 'str'> 5.37%
<class 'str'> 6.08%
<class 'str'> 6.29%
<class 'str'> 6.31%
<class 'str'> 6.53%
<class 'str'> 6.58%
<class 'str'> 5.90%
<class 'float'> nan

In [26]:
data_items = []

for item in data_list:
    year = item[0]
    government_debt_str = item[-2]
    inflation_rate_str = item[-1]
    

    if government_debt_str.endswith('%'):
        government_debt = government_debt_str.replace('%', '')

    if inflation_rate_str.endswith('%'):
        inflation_rate = inflation_rate_str.replace('%', '')

    data_items.append(
        {
        'Year': year,
        'Government Debt (%)': government_debt,
        'Inflation Rate (%)': inflation_rate
        }
    )

AttributeError: 'float' object has no attribute 'endswith'

In [ ]:
data_items[0]

In [ ]:
for item in data_items:
    print(item['Year'], item['Government Debt (%)'], item['Inflation Rate (%)'])

In [ ]:
# read data and prepare to a list of lists data

url = 'https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)_per_capita'
tables = pd.read_html(url)
data = tables[1]
data_list = data.values.tolist()[1:]
data_list[0]

In [ ]:
# create a function to convert data

def check_all_data(imf, wb, un):
    if not imf.isdigit():
        return False
    if not wb.isdigit():
        return False
    if not un.isdigit():
        return False
    return True

data_items = []

for item in data_list:
    country = item[0]
    imf = item[2]
    wb = item[4]
    un = item[6]

    if not check_all_data(imf, wb, un):
        print('skipping', country, imf, wb, un)
        continue

    if country.endswith('\u202f*'): # assume that all countries end with \u202f*
        country = country.replace('\u202f*', '')
    
    data_items.append(
        {
        'country': country,
        'imf': int(imf),
        'wb': int(wb),
        'un': int(un)
        }
    )

In [ ]:
data_items[0]

In [ ]:
data_items[-1]

In [ ]:
# process data - calculate the average GDP

processed_data = []

for item in data_items:
    avg = int(round((item['imf'] + item['wb'] + item['un'])/3, 0))

    # append each item
    processed_data.append(
        {
        'country': item['country'],
        'avg gdp pc': avg
        }
    )

In [ ]:
processed_data[-1]

In [ ]:
# write data items to csv file

import csv

with open('records_data.csv', 'w') as f:
    csv_writer = csv.DictWriter(f, fieldnames = ['country', 'avg gdp pc'])
    csv_writer.writeheader()
    csv_writer.writerows(processed_data)